default:
  phi_static: TRUE
  rho_static: TRUE
  lambda_static: NULL
  nb_likelihood: TRUE
  phi_config: "static"
  rho_config: "static"
  dir_out: "out/dm"
  nodes1: !expr c("mu_p", "z1", "size", "mu_phi", "log_rho")
  model_file: "R/nimble_dm"

phi_data:
  phi_static: FALSE
  phi_config: "data"

rho_data:
  rho_static: FALSE
  rho_config: "data"

phi_data_rho_data:
  phi_static: FALSE
  rho_static: FALSE
  phi_config: "data"
  rho_config: "data"

phi_basis_rho_static:
  phi_static: FALSE
  rho_static: TRUE
  phi_config: "basis"
  nodes1: !expr c("mu_p", "z1", "size", "mu_phi", "log_rho", "beta_p")

phi_static_rho_basis:
  phi_static: TRUE
  rho_static: FALSE
  rho_config: "basis"
  nodes1: !expr c("mu_p", "z1", "size", "mu_phi", "log_rho", "beta_r")

phi_hb_rho_static:
  phi_static: FALSE
  phi_config: "hb"
  nodes1: !expr c("mu_p", "z1", "size", "mu_phi", "mu_phi_prop", "log_rho", "tau_surv")

lambda_static_nb:
  dir_out: "out/lambda"
  phi_static: NULL
  rho_static: NULL
  lambda_static: TRUE
  nb_likelihood: TRUE
  include_all_pp: TRUE
  lambda_config: "static"
  model_file: "R/nimble_amy"
  nodes1: !expr c("mu_p", "z1", "size", "tau_p", "log_mean_r")

lambda_static_pois:
  inherits: lambda_static_nb
  nb_likelihood: FALSE

lambda_data_nb:
  inherits: lambda_static_nb
  lambda_static: FALSE
  lambda_config: "data"

lambda_data_pois:
  inherits: lambda_static_nb
  lambda_static: FALSE
  nb_likelihood: FALSE
  lambda_config: "data"

lambda_basis_nb:
  inherits: lambda_static_nb
  lambda_static: FALSE
  lambda_config: "basis"

dynamic_multi_method:
  dir_out: "out/dynamicMultiMethod"
  model_file: "R/nimble_DynamicMultiMethod"
  nb_likelihood: TRUE
  nodes1: !expr c("beta", "mu_p", "size", "sigma_p", "sigma_b", "sigma_l", "logit_p")

dynamic_multi_method_poisson:
  inherits: dynamic_multi_method
  nb_likelihood: FALSE

